// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Login struct {
	IsRemember bool   `json:"isRemember"`
	Password   string `json:"password"`
}

type NewPassword struct {
	PasswordNew string `json:"passwordNew"`
	PasswordOld string `json:"passwordOld"`
}

type NewVideo struct {
	Time string `json:"time"`
	Link string `json:"link"`
}

type Video struct {
	ID   string `json:"_id"`
	Time string `json:"time"`
	Link string `json:"link"`
}
