// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type HardwareStatistics struct {
	CPUUsage float64 `json:"cpuUsage"`
	FreeRAM  float64 `json:"freeRAM"`
	UsedRAM  float64 `json:"usedRAM"`
	TotalRAM float64 `json:"totalRAM"`
	FreeHdd  float64 `json:"freeHDD"`
	UsedHdd  float64 `json:"usedHDD"`
	TotalHdd float64 `json:"totalHDD"`
}

type Login struct {
	IsRemember bool   `json:"isRemember"`
	Password   string `json:"password"`
}

type NewPassword struct {
	PasswordNew string `json:"passwordNew"`
	PasswordOld string `json:"passwordOld"`
}

type NewReport struct {
	Level    int    `json:"level"`
	Time     string `json:"time"`
	Title    string `json:"title"`
	Body     string `json:"body"`
	IsViewed bool   `json:"isViewed"`
}

type NewVideo struct {
	Time      string `json:"time"`
	Link      string `json:"link"`
	Thumbnail string `json:"thumbnail"`
}

type RemoveReport struct {
	ID string `json:"id"`
}

type RemoveVideo struct {
	ID string `json:"id"`
}

type Report struct {
	ID       string `json:"_id"`
	Level    int    `json:"level"`
	Time     string `json:"time"`
	Title    string `json:"title"`
	Body     string `json:"body"`
	IsViewed bool   `json:"isViewed"`
}

type ReportStatistics struct {
	Normal   int `json:"normal"`
	Warnings int `json:"warnings"`
	Errors   int `json:"errors"`
}

type Video struct {
	ID        string `json:"_id"`
	Time      string `json:"time"`
	Link      string `json:"link"`
	Thumbnail string `json:"thumbnail"`
}

type ViewReport struct {
	ID string `json:"id"`
}
