// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.2
// source: proto/diagnostics.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_diagnostics_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_diagnostics_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_diagnostics_proto_rawDescGZIP(), []int{0}
}

type Diagnostic struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cpu      float64 `protobuf:"fixed64,1,opt,name=cpu,proto3" json:"cpu,omitempty"`
	FreeRAM  float64 `protobuf:"fixed64,2,opt,name=freeRAM,proto3" json:"freeRAM,omitempty"`
	UsedRAM  float64 `protobuf:"fixed64,3,opt,name=usedRAM,proto3" json:"usedRAM,omitempty"`
	TotalRAM float64 `protobuf:"fixed64,4,opt,name=totalRAM,proto3" json:"totalRAM,omitempty"`
	FreeHDD  float64 `protobuf:"fixed64,5,opt,name=freeHDD,proto3" json:"freeHDD,omitempty"`
	UsedHDD  float64 `protobuf:"fixed64,6,opt,name=usedHDD,proto3" json:"usedHDD,omitempty"`
	TotalHDD float64 `protobuf:"fixed64,7,opt,name=totalHDD,proto3" json:"totalHDD,omitempty"`
}

func (x *Diagnostic) Reset() {
	*x = Diagnostic{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_diagnostics_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Diagnostic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Diagnostic) ProtoMessage() {}

func (x *Diagnostic) ProtoReflect() protoreflect.Message {
	mi := &file_proto_diagnostics_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Diagnostic.ProtoReflect.Descriptor instead.
func (*Diagnostic) Descriptor() ([]byte, []int) {
	return file_proto_diagnostics_proto_rawDescGZIP(), []int{1}
}

func (x *Diagnostic) GetCpu() float64 {
	if x != nil {
		return x.Cpu
	}
	return 0
}

func (x *Diagnostic) GetFreeRAM() float64 {
	if x != nil {
		return x.FreeRAM
	}
	return 0
}

func (x *Diagnostic) GetUsedRAM() float64 {
	if x != nil {
		return x.UsedRAM
	}
	return 0
}

func (x *Diagnostic) GetTotalRAM() float64 {
	if x != nil {
		return x.TotalRAM
	}
	return 0
}

func (x *Diagnostic) GetFreeHDD() float64 {
	if x != nil {
		return x.FreeHDD
	}
	return 0
}

func (x *Diagnostic) GetUsedHDD() float64 {
	if x != nil {
		return x.UsedHDD
	}
	return 0
}

func (x *Diagnostic) GetTotalHDD() float64 {
	if x != nil {
		return x.TotalHDD
	}
	return 0
}

var File_proto_diagnostics_proto protoreflect.FileDescriptor

var file_proto_diagnostics_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x74,
	0x69, 0x63, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x22, 0xbe, 0x01, 0x0a, 0x0a, 0x44, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x74, 0x69,
	0x63, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x70, 0x75, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03,
	0x63, 0x70, 0x75, 0x12, 0x18, 0x0a, 0x07, 0x66, 0x72, 0x65, 0x65, 0x52, 0x41, 0x4d, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x07, 0x66, 0x72, 0x65, 0x65, 0x52, 0x41, 0x4d, 0x12, 0x18, 0x0a,
	0x07, 0x75, 0x73, 0x65, 0x64, 0x52, 0x41, 0x4d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x07,
	0x75, 0x73, 0x65, 0x64, 0x52, 0x41, 0x4d, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x52, 0x41, 0x4d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x52, 0x41, 0x4d, 0x12, 0x18, 0x0a, 0x07, 0x66, 0x72, 0x65, 0x65, 0x48, 0x44, 0x44, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x07, 0x66, 0x72, 0x65, 0x65, 0x48, 0x44, 0x44, 0x12, 0x18, 0x0a,
	0x07, 0x75, 0x73, 0x65, 0x64, 0x48, 0x44, 0x44, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x07,
	0x75, 0x73, 0x65, 0x64, 0x48, 0x44, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x48, 0x44, 0x44, 0x18, 0x07, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x48, 0x44, 0x44, 0x32, 0x35, 0x0a, 0x0b, 0x44, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x74, 0x69,
	0x63, 0x73, 0x12, 0x26, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x44, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73,
	0x74, 0x69, 0x63, 0x12, 0x06, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x0b, 0x2e, 0x44, 0x69,
	0x61, 0x67, 0x6e, 0x6f, 0x73, 0x74, 0x69, 0x63, 0x22, 0x00, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_diagnostics_proto_rawDescOnce sync.Once
	file_proto_diagnostics_proto_rawDescData = file_proto_diagnostics_proto_rawDesc
)

func file_proto_diagnostics_proto_rawDescGZIP() []byte {
	file_proto_diagnostics_proto_rawDescOnce.Do(func() {
		file_proto_diagnostics_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_diagnostics_proto_rawDescData)
	})
	return file_proto_diagnostics_proto_rawDescData
}

var file_proto_diagnostics_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_diagnostics_proto_goTypes = []interface{}{
	(*Empty)(nil),      // 0: Empty
	(*Diagnostic)(nil), // 1: Diagnostic
}
var file_proto_diagnostics_proto_depIdxs = []int32{
	0, // 0: Diagnostics.GetDiagnostic:input_type -> Empty
	1, // 1: Diagnostics.GetDiagnostic:output_type -> Diagnostic
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_diagnostics_proto_init() }
func file_proto_diagnostics_proto_init() {
	if File_proto_diagnostics_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_diagnostics_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_diagnostics_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Diagnostic); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_diagnostics_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_diagnostics_proto_goTypes,
		DependencyIndexes: file_proto_diagnostics_proto_depIdxs,
		MessageInfos:      file_proto_diagnostics_proto_msgTypes,
	}.Build()
	File_proto_diagnostics_proto = out.File
	file_proto_diagnostics_proto_rawDesc = nil
	file_proto_diagnostics_proto_goTypes = nil
	file_proto_diagnostics_proto_depIdxs = nil
}
